version: '3.9'
services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/application
    ports:
      - "8080:8080"

  postgres:
    restart: always
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: garconete123
      POSTGRES_DB: garconete
    ports:
      - "6942:5432"
