export { command as Money } from './Economy/money.js'
export { command as Avatar } from './Info/avatar.js'
export { command as BotInfo } from './Info/botinfo.js'
export { command as Daily } from './Economy/daily.js'
export { command as Anime } from './Anime/anime/index.js'
export { command as Ping } from './Info/ping.js'
export { command as Action } from './RP/action/index.js'
